{{- if .Values.httpRoute.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "myapp.fullname" . }}-httproute
  labels:
    {{- include "myapp.labels" . | nindent 4 }}
spec:
  parentRefs:
  - name: {{ include "myapp.fullname" . }}-gateway
  hostnames:
  {{- range .Values.httpRoute.hostnames }}
  - {{ . | quote }}
  {{- end }}
  rules:
  {{- range .Values.httpRoute.rules }}
  - matches:
    {{- range .matches }}
    - path:
        type: {{ .path.type }}
        value: {{ .path.value | quote }}
    {{- end }}
    backendRefs:
    {{- range .backendRefs }}
    - name: {{ include "myapp.fullname" . }}
      port: {{ .port }}
    {{- end }}
  {{- end }}
{{- end }}
